"use client";
import { useEffect,useRef,useState } from "react";
import { UploadCloud,FileText,Brain,BookOpen,MessageSquare,Layers3,Check,BarChart3,Settings2,LogOut,Plus,Sparkles,ArrowUpRight,Search,Menu,X,ChevronRight,ShieldCheck,Download } from "lucide-react";

type Role="student"|"admin"|"super_admin";
type Account={id:string;name:string;email:string;password:string;role:Role};
type Source={name:string;text:string;chunks:number;size?:number};
type Material={kind:string;data:any;provider?:string};

async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{}if(!r.ok)throw new Error(d?.error||"Something went wrong.");return d}

export default function Home(){
 const[account,setAccount]=useState<Account|null>(null),[view,setView]=useState("Dashboard"),[source,setSource]=useState<Source|null>(null),[material,setMaterial]=useState<Material|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[mobile,setMobile]=useState(false),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const a=localStorage.getItem("eduforge_session");if(a)setAccount(JSON.parse(a));const s=localStorage.getItem("eduforge_source");if(s)setSource(JSON.parse(s));const m=localStorage.getItem("eduforge_material");if(m)setMaterial(JSON.parse(m))}catch{}},[]);
 useEffect(()=>{if(source)localStorage.setItem("eduforge_source",JSON.stringify(source))},[source]);
 useEffect(()=>{if(material)localStorage.setItem("eduforge_material",JSON.stringify(material))},[material]);
 if(!account)return <Auth onLogin={a=>{localStorage.setItem("eduforge_session",JSON.stringify(a));setAccount(a)}}/>;

 async function upload(f:File){setBusy(true);setMessage("Reading your file…");try{const fd=new FormData();fd.append("file",f);const d=await api("/api/documents",{method:"POST",body:fd});setSource({name:d.name,text:d.text,chunks:d.chunks,size:d.size});setView("Documents");setMessage("Source ready.");}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.")}finally{setBusy(false)}}
 async function generate(kind:string){if(!source){input.current?.click();return}setBusy(true);setMessage("Generating "+kind+"…");try{const d=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:source.text,kind,count:10,language:"English",difficulty:"Medium",length:"Detailed"})});setMaterial({kind,data:d.data,provider:d.provider});setView(kind==="mcq"?"MCQs":kind==="qa"?"Questions":"Study Materials");setMessage("Generated successfully.");}catch(e){setMessage(e instanceof Error?e.message:"Generation failed.")}finally{setBusy(false)}}
 const logout=()=>{localStorage.removeItem("eduforge_session");setAccount(null)};
 const nav=[["Dashboard",BarChart3],["Documents",FileText],["Study Materials",BookOpen],["Questions",MessageSquare],["MCQs",Layers3],["Quizzes",Check],["AI Tutor",Brain],["Analytics",BarChart3]] as const;
 return <div className="appShell"><input hidden ref={input} type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.txt,.md,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/>
 <aside className={"appSidebar "+(mobile?"open":"")}><div className="brand"><div className="brandIcon">E</div><div><b>EduForge</b><small>AI Study Studio</small></div><button className="close" onClick={()=>setMobile(false)}><X size={16}/></button></div><button className="createBtn" onClick={()=>input.current?.click()}><Plus size={16}/> New source <span>⌘K</span></button><div className="navLabel">WORKSPACE</div>{nav.map(([n,I])=><button className={"navItem "+(view===n?"selected":"")} key={n} onClick={()=>{setView(n);setMobile(false)}}><I size={17}/>{n}</button>)}{account.role!=="student"&&<><div className="navLabel">MANAGE</div><button className={"navItem "+(view==="Admin"?"selected":"")} onClick={()=>setView("Admin")}><ShieldCheck size={17}/> Administration</button></>}<div className="sidebarBottom"><button className="navItem" onClick={()=>setView("Settings")}><Settings2 size={17}/> Settings</button><div className="account"><div>{account.name[0]}</div><span><b>{account.name}</b><small>{account.role}</small></span><button onClick={logout}><LogOut size={14}/></button></div></div></aside>
 <section className="appMain"><header className="appHeader"><div className="headerLeft"><button className="mobileMenu" onClick={()=>setMobile(true)}><Menu size={19}/></button><span>EDUFORGE</span><i>/</i><b>{view}</b></div><div className="headerRight"><div className="globalSearch"><Search size={14}/><span>Search workspace</span></div><div className="headerAvatar">{account.name[0]}</div></div></header>
 {view==="Dashboard"&&<Dashboard source={source} material={material} openUpload={()=>input.current?.click()} generate={generate}/>}
 {view==="Documents"&&<Documents source={source} openUpload={()=>input.current?.click()}/>}
 {view==="Study Materials"&&<Material material={material} generate={generate}/>}
 {view==="Questions"&&<Questions material={material}/>}
 {view==="MCQs"&&<MCQs material={material} generate={generate}/>}
 {view==="Quizzes"&&<Quiz material={material}/>}
 {view==="AI Tutor"&&<Tutor source={source}/>}
 {view==="Analytics"&&<Analytics source={source} material={material}/>}
 {view==="Admin"&&<Admin/>}{view==="Settings"&&<Settings account={account}/>}
 {message&&<div className="toast"><span>{busy?"":<Check size={13}/>}</span>{message}<button onClick={()=>setMessage("")}><X size={13}/></button></div>}</section></div>
}

function Dashboard({source,material,openUpload,generate}:any){return <main className="content"><div className="headingRow"><div><label>AI STUDY STUDIO</label><h1>Make studying <em>feel lighter.</em></h1><p>Upload your class material. EduForge transforms it into notes, questions, MCQs and practice.</p></div><button className="blackBtn" onClick={openUpload}><UploadCloud size={16}/> Add source</button></div><section className="heroPanel"><div className="heroText"><span><Sparkles size={13}/> SOURCE-GROUNDED AI</span><h2>One source.<br/><strong>Every way to learn.</strong></h2><p>Your material stays at the centre. Build a complete study pack without jumping between tools.</p><button className="blueBtn" onClick={openUpload}>Start with a file <ArrowUpRight size={15}/></button></div><div className="heroVisual"><div className="ring r1"/><div className="ring r2"/><div className="core"><Brain size={25}/><small>EDUFORGE</small><b>UNDERSTAND</b></div><div className="float one"><FileText size={15}/><b>Notes</b><Check size={13}/></div><div className="float two"><Layers3 size={15}/><b>MCQs</b><Check size={13}/></div></div></section>{source?<section className="activeSource"><div className="docIcon"><FileText size={20}/></div><div className="sourceMeta"><small>ACTIVE SOURCE</small><b>{source.name}</b><span>{source.chunks} chunks · {source.text.length.toLocaleString()} characters</span></div><button className="blackBtn" onClick={()=>generate("notes")} disabled={!source}>Generate notes <ChevronRight size={14}/></button></section>:<button className="dropArea" onClick={openUpload}><div><UploadCloud size={23}/></div><b>Drop your study file here</b><span>PDF · DOCX · PPTX · XLSX · CSV · TXT · Images</span><small>Click to browse</small></button>}<div className="sectionHead"><div><label>QUICK START</label><h3>What do you want to create?</h3></div><span>Built from your source</span></div><div className="featureGrid">{[["notes","Study notes","Structured explanations",BookOpen],["qa","Questions & answers","Exam-ready Q&A",MessageSquare],["mcq","MCQ practice","Concept + application",Layers3],["quiz","Practice quiz","Test your recall",Check]].map(([k,t,d,I]:any)=><button className="featureCard" key={k} onClick={()=>k!=="quiz"&&generate(k)}><div><I size={18}/></div><span><b>{t}</b><small>{d}</small></span><ArrowUpRight size={14}/></button>)}</div>{material&&<div className="successLine"><Check size={15}/><b>Latest {material.kind.toUpperCase()} generated</b><span>{material.provider||"EduForge AI engine"}</span></div>}</main>}

function Page({label,title,text,action,labelBtn}:any){return <div className="content"><div className="headingRow"><div><label>{label}</label><h1>{title}</h1><p>{text}</p></div>{action&&<button className="blackBtn" onClick={action}><Sparkles size={15}/>{labelBtn}</button>}</div></div>}
function Documents({source,openUpload}:any){return <main className="content"><div className="headingRow"><div><label>SOURCE LIBRARY</label><h1>Your material, <em>ready.</em></h1><p>Every file becomes a reusable source for your learning workspace.</p></div><button className="blackBtn" onClick={openUpload}><Plus size={15}/> Add source</button></div>{source?<><div className="documentCard"><div className="docIcon"><FileText size={23}/></div><div><small>DOCUMENT</small><h3>{source.name}</h3><p>{source.chunks} chunks · {source.text.length.toLocaleString()} characters</p></div><span className="ready">READY</span></div><pre className="textPreview">{source.text.slice(0,14000)}</pre></>:<Empty openUpload={openUpload} title="Your library is empty" text="Upload a PDF, presentation, spreadsheet or image to begin."/ >}</main>}
function Material({material,generate}:any){const d=material?.kind==="notes"?material.data:null;return <main className="content"><div className="headingRow"><div><label>STUDY MATERIAL</label><h1>Knowledge, <em>organized.</em></h1><p>Clean notes generated from the source you uploaded.</p></div><button className="blackBtn" onClick={()=>generate("notes")}><Sparkles size={15}/> Generate notes</button></div>{d?<article className="paper"><small>GENERATED STUDY NOTES</small><h2>{d.title||"Study Notes"}</h2>{(d.summary||[]).map((x:string,i:number)=><p className="lead" key={i}>{x}</p>)}{(d.sections||[]).map((s:any,i:number)=><section key={i}><span>0{i+1}</span><div><h3>{s.heading}</h3><p>{s.content}</p><small>Source · {s.source||"Uploaded material"}</small></div></section>)}</article>:<Empty title="No study material yet" text="Generate notes from your active source."/>}</main>}
function Questions({material}:any){const q=material?.kind==="qa"&&Array.isArray(material.data)?material.data:[];return <main className="content"><div className="headingRow"><div><label>QUESTION STUDIO</label><h1>Questions that <em>matter.</em></h1><p>Exam-style questions generated from your source.</p></div></div>{q.length?<div className="list">{q.map((x:any,i:number)=><article key={i}><b>Q{i+1}</b><div><h3>{x.question}</h3><p>{x.answer}</p><small>{x.marks||5} marks</small></div></article>)}</div>:<Empty title="No questions yet" text="Generate Q&A from the Dashboard."/>}</main>}
function MCQs({material,generate}:any){const q=material?.kind==="mcq"&&Array.isArray(material.data)?material.data:[];return <main className="content"><div className="headingRow"><div><label>MCQ STUDIO</label><h1>Practice with <em>precision.</em></h1><p>Build a question bank with answers and explanations.</p></div><button className="blackBtn" onClick={()=>generate("mcq")}><Sparkles size={15}/> Generate MCQs</button></div>{q.length?<div className="list">{q.map((x:any,i:number)=><article className="mcq" key={i}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{x.question}</h3>{x.options?.map((o:string,j:number)=><div className="option" key={j}><strong>{String.fromCharCode(65+j)}</strong>{o}</div>)}<small>{x.explanation}</small></div></article>)}</div>:<Empty title="MCQ bank is empty" text="Generate MCQs from your source."/>}</main>}
function Quiz({material}:any){const q=material?.kind==="mcq"&&Array.isArray(material.data)?material.data:[];return <main className="content"><div className="headingRow"><div><label>QUIZ MODE</label><h1>Read less. <em>Recall more.</em></h1><p>Use your generated MCQs as a focused practice round.</p></div></div>{q.length?<div className="quizCard"><div className="quizTop"><span>READY TO PRACTICE</span><b>{q.length} questions</b></div><h2>Your quiz workspace is ready.</h2><p>Question-by-question practice, answers and explanations can live here.</p><button className="blueBtn">Start quiz <ArrowUpRight size={15}/></button></div>:<Empty title="No quiz yet" text="Generate MCQs first, then practice them here."/>}</main>}
function Tutor({source}:any){const[q,setQ]=useState(""),[a,setA]=useState(""),[busy,setBusy]=useState(false);async function ask(){if(!source||!q.trim())return;setBusy(true);try{const d=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:source.text+"\nQuestion: "+q,kind:"qa",count:1,language:"English",difficulty:"Medium"})});setA(d.data?.[0]?.answer||d.data?.sections?.[0]?.content||"No answer returned.")}catch(e){setA(e instanceof Error?e.message:"Tutor error")}finally{setBusy(false)}}return <main className="content"><div className="headingRow"><div><label>AI TUTOR</label><h1>Ask your <em>material.</em></h1><p>{source?"Source-grounded help from "+source.name:"Upload a source to unlock tutoring."}</p></div></div><div className="tutorCard"><div className="tutorIcon"><Brain size={24}/></div><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Explain normalization in easy language…"/><button className="blackBtn" disabled={!source||busy} onClick={ask}>{busy?"Thinking…":"Ask EduForge"} <ArrowUpRight size={14}/></button>{a&&<div className="answer"><small>EDUFORGE ANSWER</small><p>{a}</p></div>}</div></main>}
function Analytics({source,material}:any){return <main className="content"><div className="headingRow"><div><label>ANALYTICS</label><h1>Your study <em>system.</em></h1><p>A simple snapshot of this workspace.</p></div></div><div className="stats">{[[source?1:0,"Sources"],[material?1:0,"Generated packs"],[source?.chunks||0,"Source chunks"],[material?1:0,"Recent builds"]].map(([n,t])=><div key={String(t)}><small>{t}</small><b>{n}</b><span>Current workspace</span></div>)}</div></main>}
function Admin(){return <main className="content"><div className="headingRow"><div><label>ADMINISTRATION</label><h1>Control the <em>workspace.</em></h1><p>Users, content, usage and security belong here.</p></div></div><div className="adminGrid">{["Users & roles","Content management","AI usage","Security & audit"].map(x=><div key={x}><ShieldCheck size={19}/><b>{x}</b><span>Workspace controls</span></div>)}</div></main>}
function Settings({account}:any){return <main className="content"><div className="headingRow"><div><label>SETTINGS</label><h1>Your <em>workspace.</em></h1><p>Account preferences and profile details.</p></div></div><div className="profileCard"><div>{account.name[0]}</div><section><small>ACCOUNT</small><h3>{account.name}</h3><p>{account.email}</p><span>{account.role}</span></section></div></main>}
function Empty({title,text,openUpload}:any){return <div className="empty"><Sparkles size={22}/><h3>{title}</h3><p>{text}</p>{openUpload&&<button className="blackBtn" onClick={openUpload}><UploadCloud size={15}/> Add source</button>}</div>}

function Auth({onLogin}:{onLogin:(a:Account)=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[register,setRegister]=useState(false),[name,setName]=useState(""),[error,setError]=useState("");function submit(e:any){e.preventDefault();const accounts:Account[]=JSON.parse(localStorage.getItem("eduforge_accounts")||"[]");if(register){if(!name||!email||password.length<6)return setError("Enter your name, email and a 6+ character password.");const a={id:crypto.randomUUID(),name,email,password,role:"student" as Role};localStorage.setItem("eduforge_accounts",JSON.stringify([...accounts,a]));onLogin(a)}else{const demos:Account[]=[{id:"s",name:"Demo Student",email:"student@eduforge.ai",password:"Student@123",role:"student"},{id:"a",name:"Demo Admin",email:"admin@eduforge.ai",password:"Admin@123",role:"admin"},{id:"sa",name:"Super Admin",email:"superadmin@eduforge.ai",password:"Super@123",role:"super_admin"}];const a=[...accounts,...demos].find(x=>x.email===email&&x.password===password);if(!a)return setError("Invalid email or password.");onLogin(a)}}return <main className="authPage"><div className="authShow"><div className="authBrand"><div>E</div><b>EduForge</b></div><div className="authCopy"><small>AI STUDY STUDIO</small><h1>Make knowledge<br/><em>move with you.</em></h1><p>One calm workspace for turning your PDFs, presentations and class material into something you can actually study.</p></div><div className="authMock"><div className="mockBar"><i/><i/><i/></div><div className="mockBody"><aside/><main><small>YOUR SOURCE</small><h3>Operating Systems</h3><div className="mockLine"/><div className="mockBoxes"><i/><i/><i/></div></main></div></div></div><div className="authForm"><div className="authTabs"><button className={!register?"on":""} onClick={()=>setRegister(false)}>Sign in</button><button className={register?"on":""} onClick={()=>setRegister(true)}>Create account</button></div><small>WELCOME TO EDUFORGE</small><h2>{register?"Create your study space.":"Continue learning."}</h2><p>{register?"Start with your own material and build a reusable learning system.":"Sign in to continue where you left off."}</p><form onSubmit={submit}>{register&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button>{register?"Create account":"Sign in"} <ArrowUpRight size={15}/></button></form>{error&&<div className="formError">{error}</div>}<div className="demoLogin"><b>Demo accounts</b><span>student@eduforge.ai / Student@123</span><span>admin@eduforge.ai / Admin@123</span><span>superadmin@eduforge.ai / Super@123</span></div></div></main>}
