"use client";
import {useEffect,useMemo,useState} from "react";
import {Upload,FileText,Brain,BarChart3,CheckCircle2,Sparkles,BookOpen,MessageSquare,Layers,Settings,ChevronRight,Download,RefreshCw} from "lucide-react";

type Source={id:string,name:string,text:string,chunks:number};
type Material={kind:string,data:any,provider?:string,notice?:string};
const nav=[["Dashboard",BarChart3],["Documents",FileText],["Study Materials",BookOpen],["Questions",MessageSquare],["MCQs",Layers],["Quizzes",CheckCircle2],["AI Tutor",Brain],["Analytics",BarChart3]] as const;

export default function Home(){
 const[tab,setTab]=useState("Dashboard"),[file,setFile]=useState<File|null>(null),[source,setSource]=useState<Source|null>(null),[material,setMaterial]=useState<Material|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[count,setCount]=useState(10),[quizIndex,setQuizIndex]=useState(0),[score,setScore]=useState(0),[answered,setAnswered]=useState<number|null>(null),[quizDone,setQuizDone]=useState(false);
 const mcqs=useMemo(()=>material?.kind==="mcq"&&Array.isArray(material.data)?material.data:[],[material]);
 async function upload(){
  if(!file)return;setBusy(true);setMsg("Extracting and organizing source...");
  try{const f=new FormData();f.append("file",file);const r=await fetch("/api/documents",{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);setSource({id:d.id,name:d.name,text:d.text,chunks:d.chunks});setMsg("Source ready: "+d.chunks+" chunks extracted.");setTab("Documents")}
  catch(e){setMsg(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}
 }
 async function generate(kind:string){if(!source)return;setBusy(true);setMsg("Generating "+kind+"...");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:source.text,kind,count})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMaterial({kind,data:d.data,provider:d.provider,notice:d.notice});setMsg("Generated successfully.");setTab(kind==="notes"?"Study Materials":kind==="qa"?"Questions":kind==="mcq"?"MCQs":"Study Materials")}catch(e){setMsg(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}}
 function startQuiz(){if(!mcqs.length)return;setQuizIndex(0);setScore(0);setAnswered(null);setQuizDone(false);setTab("Quizzes")}
 function answer(i:number){if(answered!==null)return;setAnswered(i);if(i===Number(mcqs[quizIndex].answer))setScore(s=>s+1)}
 function next(){if(quizIndex+1>=mcqs.length){setQuizDone(true);return}setQuizIndex(i=>i+1);setAnswered(null)}
 async function exportMaterial(){if(!material)return;const body=JSON.stringify(material.data,null,2);const r=await fetch("/api/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:"EduForge Study Material",body})});const blob=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="eduforge-study-material.html";a.click();URL.revokeObjectURL(a.href)}
 const title=tab==="Dashboard"?"Overview":tab;
 return <main className="app"><aside><div className="brand"><div className="mark">E</div><div><b>EduForge AI</b><small>Learning workspace</small></div></div><nav>{nav.map(([n,I])=><button className={tab===n?"sel":""} onClick={()=>setTab(n)} key={n}><I size={17}/>{n}</button>)}</nav><div className="asideBottom"><button onClick={()=>setTab("Settings")}><Settings size={17}/>Settings</button><div className="user"><strong>PK</strong><span>Patel Kartik<small>Student workspace</small></span></div></div></aside>
 <section className="main"><header><div><label>WORKSPACE / {title.toUpperCase()}</label><h1>{title}</h1></div><div className="actions"><div className="sourcePill">{source?"● Source ready":"○ No source"}</div><button className="dark" onClick={()=>document.getElementById("upload")?.click()}><Upload size={16}/>Upload</button></div></header>
 <input id="upload" hidden type="file" accept=".pdf,.docx,.pptx,.xls,.xlsx,.csv,.txt,.md,.jpg,.jpeg,.png,.webp" onChange={e=>{setFile(e.target.files?.[0]||null);setMsg("")}}/>
 {tab==="Dashboard"&&<><section className="welcome"><div><label><Sparkles size={13}/> AI STUDY PLATFORM</label><h2>From your files to<br/><i>exam-ready learning.</i></h2><p>Upload a real source, extract its content, then generate notes, Q&A, MCQs, flashcards and quizzes from that source.</p><button className="dark big" onClick={()=>document.getElementById("upload")?.click()}>Choose source <ChevronRight size={16}/></button></div><div className="pipeline"><span>LIVE PIPELINE</span><b>1 · Upload</b><b>2 · Extract</b><b>3 · Generate</b><b>4 · Practice</b></div></section>
 <section className="upload" onClick={()=>document.getElementById("upload")?.click()}><div className="uploadMark"><Upload/></div><h3>{file?file.name:"Choose a source file"}</h3><p>{file?"Ready to process":"PDF · DOCX · PPTX · XLSX · CSV · TXT · MD · images"}</p>{file&&<button className="dark" disabled={busy} onClick={e=>{e.stopPropagation();upload()}}>{busy?<><RefreshCw className="spin"/>Processing...</>:"Process source"}</button>}<small>{msg}</small></section>
 {source&&<section className="preview"><label>ACTIVE SOURCE</label><h3>{source.name}</h3><p>{source.chunks} chunks · {source.text.length.toLocaleString()} characters</p><div className="generator"><select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={5}>5 items</option><option value={10}>10 items</option><option value={20}>20 items</option><option value={50}>50 items</option></select><button className="dark" disabled={busy} onClick={()=>generate("notes")}>Notes</button><button className="dark" disabled={busy} onClick={()=>generate("qa")}>Q&A</button><button className="dark" disabled={busy} onClick={()=>generate("mcq")}>MCQs</button><button className="dark" disabled={busy} onClick={()=>generate("flashcards")}>Flashcards</button></div></section>}</>}
 {tab==="Documents"&&<section className="workspace"><FileText size={36}/><h2>{source?.name||"No source yet"}</h2>{source?<><p>{source.chunks} chunks extracted. This is the active source used by generation.</p><pre>{source.text.slice(0,12000)}</pre></>:<><p>Upload and process a PDF, DOCX, PPTX, spreadsheet, text file or image to create a real source.</p><button className="dark" onClick={()=>document.getElementById("upload")?.click()}>Upload source</button></>}</section>}
 {tab==="Study Materials"&&<section className="contentCard"><div className="row"><div><label>GENERATED MATERIAL</label><h2>{material?.data?.title||"No study material yet"}</h2></div>{material&&<button className="dark" onClick={exportMaterial}><Download size={15}/>Export HTML</button>}</div>{material?.kind==="notes"?<><p>{(material.data.summary||[]).join(" ")}</p>{(material.data.sections||[]).map((s:any,i:number)=><article className="section" key={i}><h3>{s.heading}</h3><p>{s.content}</p><small>Source: {s.source}</small></article>)}</>:material?.kind==="flashcards"?<div className="gridList">{(material.data||[]).map((x:any,i:number)=><article className="mini" key={i}><b>{x.front}</b><p>{x.back}</p></article>)}</div>:<Empty text="Generate Notes or Flashcards from the Dashboard."/>}</section>}
 {tab==="Questions"&&<QuestionView material={material}/>}
 {tab==="MCQs"&&<section className="contentCard"><div className="row"><div><label>GENERATED MCQS</label><h2>{mcqs.length} questions</h2></div>{mcqs.length>0&&<button className="dark" onClick={startQuiz}>Start Quiz <ChevronRight size={15}/></button>}</div>{mcqs.map((q:any,i:number)=><article className="question" key={i}><b>{i+1}. {q.question}</b>{q.options?.map((o:string,j:number)=><div className="option" key={j}><span>{String.fromCharCode(65+j)}</span>{o}</div>)}<small>{q.explanation}</small></article>)}{!mcqs.length&&<Empty text="Generate MCQs from the Dashboard."/>}</section>}
 {tab==="Quizzes"&&<section className="contentCard"><label>QUIZ MODE</label>{!mcqs.length?<Empty text="Generate MCQs first, then start the quiz."/>:quizDone?<div className="quizResult"><h2>Quiz complete</h2><p>Your score: <b>{score} / {mcqs.length}</b></p><button className="dark" onClick={startQuiz}>Retry</button></div>:<><div className="progress">Question {quizIndex+1} / {mcqs.length}</div><h2>{mcqs[quizIndex].question}</h2>{mcqs[quizIndex].options.map((o:string,i:number)=><button className={"quizOption "+(answered!==null&&i===Number(mcqs[quizIndex].answer)?"correct":"")} onClick={()=>answer(i)} key={i}>{String.fromCharCode(65+i)}. {o}</button>)}{answered!==null&&<><p className="explain">{mcqs[quizIndex].explanation}</p><button className="dark" onClick={next}>{quizIndex+1===mcqs.length?"Finish":"Next"}</button></>}</>}</section>}
 {tab==="AI Tutor"&&<Tutor source={source}/>}
 {tab==="Analytics"&&<section className="contentCard"><h2>Workspace analytics</h2><div className="stats"><div><b>{source?1:0}</b><span>Sources</span></div><div><b>{material?1:0}</b><span>Generated packs</span></div><div><b>{mcqs.length}</b><span>MCQs</span></div><div><b>{quizDone?score+"/"+mcqs.length:"—"}</b><span>Last quiz</span></div></div></section>}
 {tab==="Settings"&&<section className="contentCard"><h2>Settings</h2><p>Generation uses AI when <code>AI_API_KEY</code> is configured. Without it, the app still performs source-grounded local generation so core flows remain testable.</p></section>}
 {msg&&<div className="toast">{msg}</div>}</section></main>
}
function Empty({text}:{text:string}){return <div className="emptyBox"><Sparkles/><p>{text}</p></div>}
function QuestionView({material}:{material:Material|null}){const qs=material?.kind==="qa"&&Array.isArray(material.data)?material.data:[];return <section className="contentCard"><label>QUESTIONS & ANSWERS</label><h2>{qs.length} questions</h2>{qs.map((q:any,i:number)=><article className="question" key={i}><h3>{i+1}. {q.question}</h3><p>{q.answer}</p><small>{q.marks} marks</small></article>)}{!qs.length&&<Empty text="Generate Q&A from the Dashboard."/>}</section>}
function Tutor({source}:{source:Source|null}){const[q,setQ]=useState(""),[a,setA]=useState("");async function ask(){if(!source||!q.trim())return;setA("Thinking...");const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:source.text+"\n\nStudent question: "+q,kind:"qa",count:1})});const d=await r.json();setA(d.data?.[0]?.answer||d.data?.sections?.[0]?.content||d.error||"No answer.")}return <section className="contentCard"><label>AI TUTOR</label><h2>Ask about your uploaded source</h2><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder={source?"Ask a question from the source...":"Upload a source first."}/><button className="dark" disabled={!source} onClick={ask}>Ask AI</button>{a&&<article className="answer"><p>{a}</p></article>}</section>}
