"use client";

import AdminWorkspace from "@/components/AdminWorkspace";
import AdminStudents from "@/components/AdminStudents";
import AdminAccounts from "@/components/AdminAccounts";
import WorkspaceModule from "@/components/WorkspaceModule";
import UploadCenter from "@/components/UploadCenter";
import { useEffect, useState } from "react";
import { BarChart3, Bell, CalendarDays, Check, CheckCircle2, ClipboardCheck, Download, GraduationCap, LogOut, Menu, Settings, Users, X } from "lucide-react";

const data={Admin:["Overview","Departments","Students","Faculty","Accounts","Subjects","Master Timetable","Uploads","Leaves","Defaulters","Reports","Audit Logs","Settings"],"Super Admin":["Overview","Institutions","Administrators","Security","Audit Logs","Settings"],HOD:["Overview","Faculty","Students","Attendance Monitor","Uploads","Leaves","Defaulters","Reports","Settings"],Faculty:["Overview","Today's Lectures","Attendance","Exam Attendance","Timetable","Uploads","Leave Requests","Adjustments","Reports","Settings"],Student:["Overview","My Attendance","Timetable","Uploads","Leave Requests","Hall Tickets","Notifications","Reports","Settings"],Parent:["Overview","Attendance","Uploads","Notifications","Leave Status","Settings"]} as const;
type Role=keyof typeof data; type Status="PRESENT"|"ABSENT"|"EXAM_ONLY"|"ON_LEAVE"|"LATE_PRESENT";
type Lecture={id:string;lectureNumber:number;startTime:string;endTime:string;room?:string|null;subject:{name:string;code:string};class:{program:string;semester:number;division:string}};
type RecordItem={studentId:string;status:Status;student:{id:string;enrollmentNo:string;rollNo:string;name:string}};

export default function Portal({role,title,subtitle}:{role:Role;title:string;subtitle:string}){
 const [open,setOpen]=useState(false); const [page,setPage]=useState("Overview"); const [lectures,setLectures]=useState<Lecture[]>([]); const [currentTime,setCurrentTime]=useState(""); const [sessionId,setSessionId]=useState<string|null>(null); const [records,setRecords]=useState<RecordItem[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const items=data[role];
 useEffect(()=>{if(role!=="Faculty")return;fetch("/api/faculty/today",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(d){setLectures(d.lectures||[]);setCurrentTime(d.currentTime||"")}}).catch(()=>{})},[role]);
 async function startAttendance(id:string){setBusy(true);setMessage("");const r=await fetch("/api/attendance/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({timetableId:id})});const d=await r.json();setBusy(false);if(!r.ok){setMessage(d.error||"Unable to start attendance.");return}setSessionId(d.sessionId);setRecords(d.records);setPage("Attendance")}
 async function submit(){if(!sessionId)return;setBusy(true);const r=await fetch("/api/attendance/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId,records:records.map(x=>({studentId:x.studentId,status:x.status}))})});const d=await r.json();setBusy(false);setMessage(r.ok?`Attendance submitted. ${d.absentCount} absent notification(s) queued.`:d.error||"Submit failed.")}
 function setStatus(studentId:string,status:Status){setRecords(x=>x.map(r=>r.studentId===studentId?{...r,status}:r))}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
 const modulePage=page==="Overview"||page==="Subjects"||page==="Master Timetable"||page==="Timetable"||page==="Leaves"||page==="Leave Requests"||page==="Leave Status"||page==="Defaulters"||page==="Reports"||page==="My Attendance"||page==="Notifications"||page==="Parent Alerts"||page==="Audit Logs"||page==="Settings"||page==="Adjustments"||page==="Exam Attendance"||page==="Hall Tickets"||page==="Uploads"||page==="Faculty"||page==="Students"||page==="Attendance Monitor"||page==="Administrators"||page==="Institutions"||page==="Security";
 return <div className="portalShell"><aside className={open?"portalSide open":"portalSide"}><div className="portalBrand"><div className="brandMark"><GraduationCap size={21}/></div><div><b>Noble</b><span>Group of Institutions</span></div><button className="iconBtn mobileOnly" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="campusCard"><div className="campusLogo">NGI</div><div><b>Noble Campus</b><small>Academic Year 2026–27</small></div></div><div className="navLabel">PORTAL</div>{items.map(x=><button key={x} className={page===x?"navItem active":"navItem"} onClick={()=>{setPage(x);setOpen(false);if(x!=="Attendance")setSessionId(null)}}>{x.includes("Attendance")||x.includes("Lectures")?<ClipboardCheck size={16}/>:x.includes("Timetable")?<CalendarDays size={16}/>:x.includes("Report")?<BarChart3 size={16}/>:x.includes("Faculty")||x.includes("Students")||x.includes("Institutions")?<Users size={16}/>:x.includes("Notification")?<Bell size={16}/>:<Settings size={16}/>}<span>{x}</span></button>)}<div className="portalBottom"><div className="portalUser"><div className="avatar">NG</div><div><b>{role}</b><small>Noble Group of Institutions</small></div></div><button className="logoutBtn" onClick={logout}><LogOut size={15}/> Sign out</button></div></aside><main className="portalMain"><header className="portalTop"><button className="iconBtn mobileOnly" onClick={()=>setOpen(true)}><Menu size={20}/></button><span>NGI / {page}</span><div className="portalTopRight"><Bell size={18}/><div className="topAvatar">NG</div></div></header><section className="portalContent">
 {page==="Departments"&&role==="Admin"?<AdminWorkspace/>:page==="Students"&&role==="Admin"?<AdminStudents/>:page==="Accounts"&&role==="Admin"?<AdminAccounts/>:page==="Today's Lectures"&&role==="Faculty"?<FacultyToday lectures={lectures} currentTime={currentTime} onStart={startAttendance} busy={busy}/>:page==="Hall Tickets"&&role==="Student"?<HallTickets/>:page==="Uploads"?<UploadCenter role={role}/>:page==="Attendance"&&role==="Faculty"&&sessionId?<LiveAttendance records={records} setStatus={setStatus} onSubmit={submit} busy={busy} message={message}/>:modulePage?<WorkspaceModule role={role} page={page}/>:<div className="card emptyState">Workspace ready.</div>}
 </section></main></div>
}

function HallTickets(){
 const [data,setData]=useState<any>({});
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/exam/hall-ticket",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load hall tickets.");setData(d)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load hall tickets.")).finally(()=>setLoading(false))},[]);
 const openTicket=(id:string)=>window.open("/api/exam/hall-ticket?sessionId="+encodeURIComponent(id),"_blank","noopener,noreferrer");
 return <div className="adminWorkspace"><div className="pageHead"><div><span className="eyebrow">STUDENT · EXAMINATION</span><h1>Hall <em>tickets.</em></h1><p>Generate your official examination hall ticket from the published exam schedule.</p></div></div>{loading?<div className="card emptyState">Loading examination schedule…</div>:error?<div className="card loginError">{error}</div>:(data.exams||[]).length===0?<div className="card emptyState"><h2>No hall tickets yet.</h2><p>Your faculty or examination authority has not published an exam schedule for your division.</p></div>:<div className="lectureStack">{data.exams.map((x:any)=><div className="lectureCard" key={x.id}><div className="lectureTime"><CalendarDays size={18}/><b>{x.examType.replace("_"," ")}</b></div><div className="lectureInfo"><span>{data.student?.program} · Semester {data.student?.semester} · Division {data.student?.division}</span><h2>{x.subject.code} · {x.subject.name}</h2><small>{x.dateKey} · {x.room}</small></div><button className="primary" onClick={()=>openTicket(x.id)}>Generate Hall Ticket <Download size={14}/></button></div>)}</div>}</div>
}

function FacultyToday({lectures,currentTime,onStart,busy}:{lectures:Lecture[];currentTime:string;onStart:(id:string)=>void;busy:boolean}){return <><div className="pageHead"><div><span className="eyebrow">FACULTY · TODAY · {currentTime||"--:--"}</span><h1>Today's <em>lectures.</em></h1><p>Automatically loaded from your Monday–Saturday timetable.</p></div></div><div className="lectureStack">{lectures.length?lectures.map((l,i)=><div className="lectureCard current" key={l.id}><div className="lectureTime"><ClipboardCheck size={18}/><b>Lecture {l.lectureNumber}</b>{i===0&&<span>READY</span>}</div><div className="lectureInfo"><span>{l.class.program} · Semester {l.class.semester} · Division {l.class.division}</span><h2>{l.subject.name}</h2><small>{l.startTime} – {l.endTime} · {l.room||"Room not assigned"}</small></div><button className="primary" onClick={()=>onStart(l.id)} disabled={busy}>Start Attendance</button></div>):<div className="card"><h2>No lectures assigned for today.</h2><p>Admin can update the master timetable; your dashboard reflects it automatically.</p></div>}</div></>}

function LiveAttendance({records,setStatus,onSubmit,busy,message}:{records:RecordItem[];setStatus:(id:string,s:Status)=>void;onSubmit:()=>void;busy:boolean;message:string}){const count=(s:Status)=>records.filter(x=>x.status===s).length;return <><div className="pageHead"><div><span className="eyebrow">LIVE ATTENDANCE · {records.length} STUDENTS</span><h1>Mark <em>attendance.</em></h1><p>Default is Present. Change only the required status.</p></div><button className="primary" onClick={onSubmit} disabled={busy}>Submit Attendance <Check size={15}/></button></div><div className="attendanceStats"><span>Present <b>{count("PRESENT")}</b></span><span>Absent <b>{count("ABSENT")}</b></span><span>Exam Only <b>{count("EXAM_ONLY")}</b></span><span>On Leave <b>{count("ON_LEAVE")}</b></span><span>Late <b>{count("LATE_PRESENT")}</b></span></div><div className="card attendanceTable"><div className="tableHead"><span>ROLL</span><span>STUDENT</span><span>STATUS</span><span>QUICK ACTION</span></div>{records.map(r=><div className="tableRow" key={r.studentId}><span className="roll">{r.student.rollNo}</span><div className="studentCell"><div className="avatar">{r.student.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>{r.student.name}</b><small>{r.student.enrollmentNo}</small></div></div><span className={`status ${r.status.toLowerCase().replace("_","-")}`}>{r.status.replace("_"," ")}</span><div className="statusButtons">{(["PRESENT","ABSENT","EXAM_ONLY","ON_LEAVE","LATE_PRESENT"] as Status[]).map(s=><button key={s} className={r.status===s?"chosen":""} onClick={()=>setStatus(r.studentId,s)}>{s==="PRESENT"?"P":s==="ABSENT"?"A":s==="EXAM_ONLY"?"E":s==="ON_LEAVE"?"L":"LT"}</button>)}</div></div>)}</div>{message&&<div className="toast"><CheckCircle2 size={15}/>{message}</div>}</>}
