"use client";
import { FormEvent,useState } from "react";
import { ArrowRight, CheckCircle2, Copy, GraduationCap, Mail, Phone, ShieldCheck, UserRound } from "lucide-react";

export default function SignupPage(){
 const [name,setName]=useState("");const [enrollment,setEnrollment]=useState("");const [mobile,setMobile]=useState("");const [email,setEmail]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [credentials,setCredentials]=useState<{studentId:string;password:string}|null>(null);
 async function submit(e:FormEvent){e.preventDefault();setMessage("");setBusy(true);try{const r=await fetch("/api/auth/signup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({enrollment,name,mobile,email})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create account.");setCredentials({studentId:d.studentId,password:d.password});}catch(e){setMessage(e instanceof Error?e.message:"Unable to create account.")}finally{setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value)}catch{}}
 if(credentials) return <main className="authPage"><section className="authVisual"><div className="authOrb one"/><div className="authOrb two"/><div className="authVisualInner"><a href="/" className="authBrand"><span className="authLogo"><img src="/noble-logo.jpg" alt="Noble Group of Institutions"/></span><span><b>Noble</b><small>Digital Campus</small></span></a><div className="authMessage"><span className="corpKicker">ACCOUNT READY</span><h1>Welcome to<br/><em>Noble Digital Campus.</em></h1><p>Your student login has been generated. Save these credentials somewhere safe before continuing.</p><div className="authFeature"><CheckCircle2 size={17}/><span><b>Student ID confirmed</b><small>Your official enrollment number is your login ID.</small></span></div><div className="authFeature"><ShieldCheck size={17}/><span><b>Password generated</b><small>The password is shown here once.</small></span></div></div></div></section><section className="authPanel"><div className="authBox"><span className="corpKicker dark">GENERATED CREDENTIALS</span><h2>You're all set.</h2><p className="authMuted">Copy both values before leaving this page.</p><div className="card" style={{marginTop:18}}><div className="eyebrow">STUDENT ID</div><div style={{fontSize:21,fontWeight:800,marginTop:7}}>{credentials.studentId}</div><button className="secondaryBtn" style={{marginTop:10}} type="button" onClick={()=>copy(credentials.studentId)}><Copy size={14}/> Copy ID</button></div><div className="card" style={{marginTop:12}}><div className="eyebrow">PASSWORD</div><div style={{fontSize:19,fontWeight:800,marginTop:7}}>{credentials.password}</div><button className="secondaryBtn" style={{marginTop:10}} type="button" onClick={()=>copy(credentials.password)}><Copy size={14}/> Copy password</button></div><a className="authSubmit" style={{textDecoration:"none",marginTop:16}} href="/login?role=STUDENT">Continue to student login <ArrowRight size={16}/></a><a className="authBack" style={{display:"block",marginTop:14}} href="/login">← Back to login</a></div></section></main>;
 return <main className="authPage"><section className="authVisual"><div className="authOrb one"/><div className="authOrb two"/><div className="authVisualInner"><a href="/" className="authBrand"><span className="authLogo"><img src="/noble-logo.jpg" alt="Noble Group of Institutions"/></span><span><b>Noble</b><small>Digital Campus</small></span></a><div className="authMessage"><span className="corpKicker">STUDENT ACCOUNT</span><h1>Activate your<br/><em>campus access.</em></h1><p>Use the enrollment details already registered by Noble Administration. Your Student ID is your enrollment number and the system generates the password for you.</p><div className="authFeature"><GraduationCap size={17}/><span><b>Institution controlled</b><small>You can activate only an official student record.</small></span></div><div className="authFeature"><ShieldCheck size={17}/><span><b>Credentials generated securely</b><small>Your password is stored only as a secure hash.</small></span></div></div></div></section><section className="authPanel"><div className="authBox"><a href="/login" className="authBack">← Back to sign in</a><span className="corpKicker dark">CREATE ACCOUNT</span><h2>Activate student account.</h2><p className="authMuted">Enter the enrollment and registered mobile number provided by your institution.</p><form onSubmit={submit} style={{marginTop:20}}><label>Full name</label><div className="authInput"><UserRound size={15} style={{marginLeft:10,color:"#98a2b3"}}/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div><label>Enrollment / Student ID</label><div className="authInput"><GraduationCap size={15} style={{marginLeft:10,color:"#98a2b3"}}/><input required value={enrollment} onChange={e=>setEnrollment(e.target.value.trim())} placeholder="NOBLE-BCA-001"/></div><label>Registered mobile number</label><div className="authInput"><Phone size={15} style={{marginLeft:10,color:"#98a2b3"}}/><input required inputMode="numeric" maxLength={10} value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,""))} placeholder="10-digit mobile number"/></div><label>Email <span style={{fontWeight:400,color:"#98a2b3"}}>(optional)</span></label><div className="authInput"><Mail size={15} style={{marginLeft:10,color:"#98a2b3"}}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div>{message&&<div className="authError">{message}</div>}<button className="authSubmit" disabled={busy}>{busy?"Generating credentials…":"Create account & generate password"}<ArrowRight size={16}/></button></form><small className="authLegal">If your Student ID is not recognised, contact Noble Administration to create the student record first.</small></div></section></main>;
}
