<?php
require __DIR__.'/../../bootstrap.php';require_role(['SUPER_ADMIN','ADMIN','HOD']);
$pdo=Database::connection();$title='Student Management';
$q=trim((string)($_GET['q']??''));$status=$_GET['status']??'';$dept=(int)($_GET['department_id']??0);
$sql="SELECT s.*,d.name department,p.name program,se.number semester,v.name division FROM students s LEFT JOIN departments d ON d.id=s.department_id LEFT JOIN programs p ON p.id=s.program_id LEFT JOIN semesters se ON se.id=s.semester_id LEFT JOIN divisions v ON v.id=s.division_id WHERE 1=1";$params=[];
if($q!==''){$sql.=" AND (s.enrollment_no LIKE :q OR s.admission_no LIKE :q OR s.first_name LIKE :q OR s.last_name LIKE :q OR s.mobile LIKE :q)";$params['q']="%$q%";}
if($status!==''){$sql.=" AND s.status=:status";$params['status']=$status;}
if($dept>0){$sql.=" AND s.department_id=:dept";$params['dept']=$dept;}
$sql.=" ORDER BY s.id DESC LIMIT 200";$st=$pdo->prepare($sql);$st->execute($params);$students=$st->fetchAll();$departments=$pdo->query("SELECT id,name FROM departments WHERE active=1 ORDER BY name")->fetchAll();$flash=take_flash();
require __DIR__.'/../../views/layout/header.php';
?><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="eyebrow">PEOPLE · STUDENT MANAGEMENT</div><h1 class="fw-bold mb-1">Students.</h1><p class="text-secondary mb-0">Real student records stored in MySQL.</p></div><a class="btn btn-primary" href="/students/form.php"><i class="bi bi-plus-lg me-1"></i>Add Student</a></div>
<?php if($flash):?><div class="alert alert-<?=e($flash[0])?>"><?=e($flash[1])?></div><?php endif;?>
<div class="card table-card"><div class="card-body"><form class="row g-2 mb-3"><div class="col-md-5"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Search ID, enrollment, name or mobile"></div><div class="col-md-3"><select class="form-select" name="department_id"><option value="0">All departments</option><?php foreach($departments as $d):?><option value="<?=$d['id']?>" <?=$dept===$d['id']?'selected':''?>><?=e($d['name'])?></option><?php endforeach;?></select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All status</option><?php foreach(['ACTIVE','INACTIVE','GRADUATED','SUSPENDED','TRANSFERRED','DROPOUT'] as $x):?><option <?=$status===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-outline-primary flex-fill">Filter</button><a class="btn btn-outline-secondary" href="/students/index.php">Reset</a></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Enrollment</th><th>Academic</th><th>Mobile</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$students):?><tr><td colspan="6" class="text-center py-5 text-secondary">No students found.</td></tr><?php else: foreach($students as $s):?><tr><td><strong><?=e(trim($s['first_name'].' '.$s['middle_name'].' '.$s['last_name']))?></strong><div class="small text-secondary">ID <?=e($s['user_id']??'—')?></div></td><td><?=e($s['enrollment_no'])?><div class="small text-secondary"><?=e($s['admission_no']??'')?></div></td><td><?=e($s['program']??'—')?> · Sem <?=e($s['semester']??'—')?> · <?=e($s['division']??'—')?></td><td><?=e($s['mobile']??'—')?></td><td><span class="badge text-bg-<?=$s['status']==='ACTIVE'?'success':'secondary'?>"><?=e($s['status'])?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="/students/form.php?id=<?=$s['id']?>">View / Edit</a></td></tr><?php endforeach;endif;?></tbody></table></div></div></div><?php require __DIR__.'/../../views/layout/footer.php';