<?php
require __DIR__.'/../../bootstrap.php';require_role(['SUPER_ADMIN','ADMIN']);
$pdo=Database::connection();$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['_csrf']??null);try{$a=$_POST['action']??'';
 if($a==='department'){$st=$pdo->prepare('INSERT INTO departments(institution_id,name,code) SELECT id,?,? FROM institutions ORDER BY id LIMIT 1');$st->execute([trim($_POST['name']),strtoupper(trim($_POST['code']))]);}
 elseif($a==='program'){$st=$pdo->prepare('INSERT INTO programs(department_id,name,code,duration_years,degree_type) VALUES(?,?,?,?,?)');$st->execute([(int)$_POST['department_id'],trim($_POST['name']),strtoupper(trim($_POST['code'])),($_POST['duration']?:null),trim($_POST['degree_type'])]);}
 elseif($a==='semester'){$st=$pdo->prepare('INSERT INTO semesters(program_id,number,academic_year,start_date,end_date) VALUES(?,?,?,?,?)');$st->execute([(int)$_POST['program_id'],(int)$_POST['number'],trim($_POST['academic_year']),($_POST['start_date']?:null),($_POST['end_date']?:null)]);}
 elseif($a==='division'){$st=$pdo->prepare('INSERT INTO divisions(semester_id,name,capacity) VALUES(?,?,?)');$st->execute([(int)$_POST['semester_id'],trim($_POST['name']),($_POST['capacity']?:null)]);}
 flash('success','Academic structure saved successfully.');redirect('/academic/index.php');
 }catch(Throwable $e){$error=$e instanceof PDOException&&$e->getCode()==='23000'?'This code/name already exists at this level.':$e->getMessage();}}
$departments=$pdo->query('SELECT * FROM departments WHERE active=1 ORDER BY name')->fetchAll();$programs=$pdo->query('SELECT p.*,d.name department FROM programs p JOIN departments d ON d.id=p.department_id WHERE p.active=1 ORDER BY d.name,p.name')->fetchAll();$semesters=$pdo->query('SELECT s.*,p.name program FROM semesters s JOIN programs p ON p.id=s.program_id ORDER BY p.name,s.number')->fetchAll();$divisions=$pdo->query('SELECT v.*,s.number semester,p.name program FROM divisions v JOIN semesters s ON s.id=v.semester_id JOIN programs p ON p.id=s.program_id ORDER BY p.name,s.number,v.name')->fetchAll();$title='Academic Management';$flash=take_flash();require __DIR__.'/../../views/layout/header.php';
?><div class="d-flex justify-content-between align-items-center mb-4"><div><div class="eyebrow">ACADEMICS · HIERARCHY</div><h1 class="fw-bold">Academic structure.</h1><p class="text-secondary mb-0">Department → Program → Semester → Division.</p></div></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($flash):?><div class="alert alert-success"><?=e($flash[1])?></div><?php endif;?><div class="row g-4">
<div class="col-xl-6"><div class="card table-card p-4"><h5>Add Department</h5><form method="post" class="row g-2"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="department"><div class="col-8"><input required name="name" class="form-control" placeholder="Computer Science"></div><div class="col-4"><input required name="code" class="form-control" placeholder="CSE"></div><div class="col-12"><button class="btn btn-primary">Create Department</button></div></form><hr><div class="table-responsive"><table class="table"><thead><tr><th>Name</th><th>Code</th></tr></thead><tbody><?php foreach($departments as $d):?><tr><td><?=e($d['name'])?></td><td><?=e($d['code'])?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-6"><div class="card table-card p-4"><h5>Add Program</h5><form method="post" class="row g-2"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="program"><div class="col-12"><select required name="department_id" class="form-select"><option value="">Department</option><?php foreach($departments as $d):?><option value="<?=$d['id']?>"><?=e($d['name'])?></option><?php endforeach;?></select></div><div class="col-8"><input required name="name" class="form-control" placeholder="BCA"></div><div class="col-4"><input required name="code" class="form-control" placeholder="BCA"></div><div class="col-6"><input name="duration" type="number" step=".5" class="form-control" placeholder="Duration years"></div><div class="col-6"><input name="degree_type" class="form-control" placeholder="Degree type"></div><div class="col-12"><button class="btn btn-primary">Create Program</button></div></form><hr><?php foreach($programs as $p):?><div class="d-flex justify-content-between border-bottom py-2"><span><?=e($p['name'])?></span><small class="text-secondary"><?=e($p['department'])?> · <?=e($p['code'])?></small></div><?php endforeach;?></div></div>
<div class="col-xl-6"><div class="card table-card p-4"><h5>Add Semester</h5><form method="post" class="row g-2"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="semester"><div class="col-12"><select required name="program_id" class="form-select"><option value="">Program</option><?php foreach($programs as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?> · <?=e($p['department'])?></option><?php endforeach;?></select></div><div class="col-4"><input required name="number" type="number" min="1" max="20" class="form-control" placeholder="Semester"></div><div class="col-8"><input required name="academic_year" class="form-control" value="2026-27"></div><div class="col-6"><input name="start_date" type="date" class="form-control"></div><div class="col-6"><input name="end_date" type="date" class="form-control"></div><div class="col-12"><button class="btn btn-primary">Create Semester</button></div></form><hr><?php foreach($semesters as $s):?><div class="d-flex justify-content-between border-bottom py-2"><span>Semester <?=e($s['number'])?></span><small><?=e($s['program'])?> · <?=e($s['academic_year'])?></small></div><?php endforeach;?></div></div>
<div class="col-xl-6"><div class="card table-card p-4"><h5>Add Division</h5><form method="post" class="row g-2"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="division"><div class="col-8"><select required name="semester_id" class="form-select"><option value="">Semester</option><?php foreach($semesters as $s):?><option value="<?=$s['id']?>"><?=e($s['program'])?> · Sem <?=e($s['number'])?></option><?php endforeach;?></select></div><div class="col-4"><input required name="name" class="form-control" placeholder="A"></div><div class="col-8"><input name="capacity" type="number" class="form-control" placeholder="Capacity"></div><div class="col-4"><button class="btn btn-primary w-100">Create</button></div></form><hr><?php foreach($divisions as $v):?><div class="d-flex justify-content-between border-bottom py-2"><span>Division <?=e($v['name'])?></span><small><?=e($v['program'])?> · Sem <?=e($v['semester'])?></small></div><?php endforeach;?></div></div>
</div><?php require __DIR__.'/../../views/layout/footer.php';